### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by jmikkola** [eguven/python3-memcached#10]

**Comment by xmnlab** [comment]
Hi everybody,

I am packaging this lib on conda-forge and I need the license of this project.

On pypi I saw that this project is under a OSI license .. so I think it is ok to build that on conda-forge (accepted license: https://opensource.org/licenses/alphabetical).

can you provide a file like LICENSE with the license of the project?

**Comment by xmnlab** [comment]
well I saw a way to create manually the license file in the conda package.

I think your license is: https://opensource.org/licenses/Python-2.0

right?

**Comment by eguven** [comment]
You really shouldn't package this, see the note about deprecation and the parent package compatibility: https://github.com/eguven/python3-memcached/blob/master/README#L1

**Comment by xmnlab** [comment]
I see ... thank you.
